# Configuración para GitHub Pages
# Este archivo no es necesario para GitHub Pages pero se mantiene como documentación

# La aplicación funciona completamente en el frontend
# Archivos principales:
# - index.html (página de login)
# - dashboard.html (página principal)
# - auth-netlify.js (autenticación local)
# - script.js (lógica principal)
# - style.css + login.css (estilos)

# GitHub Pages servirá automáticamente index.html como página principal
